# Grid Maze: 
# n_cols * n_rows: size of the maze, the number of squares
# edge: the length of the edge of each square
# walls: the positions of walls as the components of the environment


## number of grids
n_cols: 9
n_rows: 8
## size of every grid
edge: 80


## positions of walls
walls: !!set
  {
  !!python/tuple [5, 8],
  !!python/tuple [5, 7],
  !!python/tuple [5, 6],
  !!python/tuple [6, 5],
  !!python/tuple [4, 4],
  !!python/tuple [6, 4], 
  !!python/tuple [3, 4],
  !!python/tuple [1, 4], 
  !!python/tuple [3, 6],
  !!python/tuple [3, 7],
  !!python/tuple [3, 8],
  !!python/tuple [5, 3],
  !!python/tuple [5, 1],
  !!python/tuple [8, 7],
  !!python/tuple [7, 7],
  !!python/tuple [9, 6],
}


## objects in environment (excluding the agent)
## traps, not terminal
traps: !!python/object:objects.ObjectGroup
  name: 'traps'
  members:
    - !!python/object:objects.Trap
      position: !!python/tuple [7, 5]
      color: [1,0.5,0]
      proportion: 0.4
    - !!python/object:objects.Trap
      position: !!python/tuple [1, 3]
      color: [1,0.5,0]
      proportion: 0.4
    - !!python/object:objects.Trap
      position: !!python/tuple [8, 1]
      color: [1,0.5,0]
      proportion: 0.4

    - !!python/object:objects.Trap
      position: !!python/tuple [7, 3]
      color: [1,0.5,0]
      proportion: 0.4

## deathtraps, terminal
deathtrap1: !!python/object:objects.DeathTrap
      position: !!python/tuple [2, 4]
      color: [.8,0,0.5]
      proportion: 0.45

deathtrap2: !!python/object:objects.DeathTrap
      position: !!python/tuple [5, 2]
      color: [.8,0,0.5]
      proportion: 0.45

deathtrap3: !!python/object:objects.DeathTrap
      position: !!python/tuple [2, 1]
      color: [.8,0,0.5]
      proportion: 0.45


## button, not terminal
button1: !!python/object:objects.Button
  name: 'button'
  position: !!python/tuple [4, 7]
  color: [0.1,0.2,0.8]
  proportion: 0.2

button2: !!python/object:objects.Button
  name: 'button'
  position: !!python/tuple [1, 1]
  color: [0.1,0.2,0.8]
  proportion: 0.2

## gold, terminal
gold: !!python/object:objects.Gold
  name: 'gold'
  position: !!python/tuple [9, 7]
  color: [1,0.8,0]
  proportion: 0.4

