# Grid Maze: 
# n_cols * n_rows: size of the maze, the number of squares
# edge: the length of the edge of each square
# walls: the positions of walls as the components of the environment


## number of grids
n_cols: 6
n_rows: 6
## size of every grid
edge: 80


## positions of walls
walls: !!set
  {!!python/tuple [1, 5],
  !!python/tuple [3, 5],
  !!python/tuple [4, 5],
  !!python/tuple [5, 3],
  !!python/tuple [6, 3]}


## objects in environment (excluding the agent)
## traps, not terminal
traps:
  - !!python/object:objects.Trap
    position: !!python/tuple
      [4, 2]
    color: [1,0.5,0]
    size: 30
  - !!python/object:objects.Trap
    position: [2, 3]
    color: [1,0.5,0]
    size: 30

## deathtraps, terminal
deathtraps:
  - !!python/object:objects.DeathTrap
    position:  !!python/tuple
      [4, 4]
    color: [.8,0,0.5]
    size: 30

  - !!python/object:objects.DeathTrap
    position:  !!python/tuple
      [1, 1]
    color: [.8,0,0.5]
    size: 30


## gold, terminal
gold: !!python/object:objects.Gold
  name: 'gold'
  position: !!python/tuple
    [5, 1]
  color: [1,0.8,0]
  size: 30

